spring:
  profiles:
    active: dev
  application:
    name: sentinel-sample
logging:
  level:
    com.itdom.cloud: debug
  file:
    path: ./logs/sentinel-sample
    name: ${logging.file.path}/${spring.application.name}.log