spring:
  profiles:
    active: dev
  application:
    name: order-nacos
  cloud:
    nacos:
      server-addr: 192.168.6.108:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev
        ephemeral: false #是否时永久实例，如果宕机了也不会删除实例
#        metadata: version=1
#        weight: 1 权重，用来区分服务的优先级，通常和负载均衡策略相关联，权重越大那么分到的流量就越大。
#        group: 分组，用来做更加细致的区分，相对与namespace更加细
#        service: ${spring.application.name}是默认的名字，也就是服务的名称
logging:
  level:
    com.itdom.cloud: debug
  file:
    path: ./logs/order-nacos
    name: ${logging.file.path}/${spring.application.name}.log